DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS (
   ID BIGSERIAL PRIMARY KEY,
   AUTHOR VARCHAR(255)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES (
   ID BIGSERIAL PRIMARY KEY,
   GENRE VARCHAR(255)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
  ID BIGSERIAL PRIMARY KEY,
  TITLE VARCHAR(255),
  AUTHOR_ID BIGINT,
  GENRE_ID BIGINT,
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID),
  FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
);